# -*- coding: utf-8 -*-
"""ImageToCartoon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GDBKxDOpegU2FwwtxvG-O6qkoG276OBX

**Image Cartoonify using Python**
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from google.colab import files

"""Load Image"""

def read_file(filename):
  img = cv2.imread(filename)
  cv2_imshow(img)
  return img

def color_quantization(img, k):
# Transform the image
  data = np.float32(img).reshape((-1, 3))

# Determine criteria
  criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 20, 0.001)

# Implementing K-Means
  ret, label, center = cv2.kmeans(data, k, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)
  center = np.uint8(center)
  result = center[label.flatten()]
  result = result.reshape(img.shape)
  return result

"""**Creating Edge Mask**

using c*v2.adaptiveThreshold()*




"""

def edge_mask(img, line_size, blur_value):
  gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
  gray_blur = cv2.medianBlur(gray, blur_value)
  edges = cv2.adaptiveThreshold(gray_blur, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, line_size, blur_value)
  return edges

uploaded = files.upload()

filename = next(iter(uploaded))
img = read_file(filename)

line_size = 7
blur_value = 7

edges = edge_mask(img, line_size, blur_value)
cv2_imshow(edges)

"""Reducing the Color Palette"""

def color_quantization(img, k):
# Transform the image
  data = np.float32(img).reshape((-1, 3))

# Determine criteria
  criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 20, 0.001)

# Implementing K-Means
  ret, label, center = cv2.kmeans(data, k, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)
  center = np.uint8(center)
  result = center[label.flatten()]
  result = result.reshape(img.shape)
  return result

total_color = 9
img = color_quantization(img, total_color)

"""Bilateral Filter"""

blurred = cv2.bilateralFilter(img, d=7, sigmaColor=200,sigmaSpace=200)

"""Combining Edge Mask with Colored Image"""

cartoon = cv2.bitwise_and(blurred, blurred, mask=edges)

total_color = 9

img = color_quantization(img, total_color)
cv2_imshow(img)

